"""initial schema

Revision ID: 15a7f0aea99b
Revises: 
Create Date: 2026-09-06 00:28:25.053966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a7f0aea99b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('change_type', sa.Enum('NEW_ACT', 'NEW_SUBSIDIARY_LEGISLATION', 'CLAUSE_AMENDMENT', 'CLAUSE_ADDITION', 'CLAUSE_REMOVAL', name='changetype'), nullable=False),
    sa.Column('statute_id', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('old_text', sa.String(), nullable=True),
    sa.Column('new_text', sa.String(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('general_effects', sa.String(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('practice_area', sa.String(), nullable=False),
    sa.Column('current_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statute_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('statute_id', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affected_documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('change_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('highlighted_portion', sa.String(), nullable=True),
    sa.Column('citation', sa.String(), nullable=True),
    sa.Column('suggested_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amendment_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('affected_document_id', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('AGREED', 'REJECTED', name='decision'), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=False),
    sa.Column('generated_document_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['affected_document_id'], ['affected_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amendment_decisions')
    op.drop_table('affected_documents')
    op.drop_table('statute_snapshots')
    op.drop_table('documents')
    op.drop_table('changes')
    # ### end Alembic commands ###
