"""add conversation_history to affected_documents

Revision ID: 7f5418f4ff62
Revises: 15a7f0aea99b
Create Date: 2026-09-06 04:38:27.615048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5418f4ff62'
down_revision: Union[str, Sequence[str], None] = '15a7f0aea99b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affected_documents', sa.Column('conversation_history', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('affected_documents', 'conversation_history')
    # ### end Alembic commands ###
