"""add summary_unverified to changes

Revision ID: 87f6b748c5a9
Revises: 7f5418f4ff62
Create Date: 2026-09-06 09:48:35.803278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f6b748c5a9'
down_revision: Union[str, Sequence[str], None] = '7f5418f4ff62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'changes',
        sa.Column('summary_unverified', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('changes', 'summary_unverified')
    # ### end Alembic commands ###
